# Generated by Django 3.0.1 on 2021-11-09 18:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultas', '0001_initial'),
        ('medicamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.Consulta')),
            ],
            options={
                'verbose_name': 'Recetas Medicas',
                'verbose_name_plural': 'Recetas Medicas',
                'db_table': 'receta',
            },
        ),
        migrations.CreateModel(
            name='MedicamentosRecetados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescripcion', models.TextField()),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicamentos.Medicamento')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receta.Receta')),
            ],
            options={
                'verbose_name': 'Detalle Receta Medica',
                'verbose_name_plural': 'Detalles Recetas Medicas',
                'db_table': 'detallereceta',
            },
        ),
    ]
