# Generated by Django 3.0.1 on 2021-11-09 18:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100, verbose_name='Nombres')),
                ('Apellido', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('Teléfono', models.CharField(max_length=500)),
                ('Fecha_de_Cumpleaños', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('Direccion', models.CharField(max_length=50, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Control de Registro de Pacientes',
                'verbose_name_plural': 'Control de Registro de Paciente',
                'db_table': 'paciente',
                'ordering': ['Nombre'],
            },
        ),
    ]
