# Generated by Django 3.0.1 on 2021-11-09 18:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('presentacion', models.CharField(max_length=100)),
                ('volumen', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Medicamentos',
                'verbose_name_plural': 'Medicamentos',
                'db_table': 'medicamento',
            },
        ),
    ]
